start spinavbatchfilelines.exe ""
rem start spinavbatchfilelines.exe "guitar"
rem start spinavbatchfilelines.exe "kick"
rem start spinavbatchfilelines.exe "drum"
rem start spinavbatchfilelines.exe "kit"
rem start spinavbatchfilelines.exe "synth"
rem start spinavbatchfilelines.exe "bass"